(((min-height . 16) (min-width . 30) (min-height-ignore . 12) (min-width-ignore . 12) (min-height-safe . 4) (min-width-safe . 6)
  (min-pixel-height . 336) (min-pixel-width . 300) (min-pixel-height-ignore . 252) (min-pixel-width-ignore . 120) (min-pixel-height-safe . 84) (min-pixel-width-safe . 60))
 vc (pixel-width . 1896) (pixel-height . 999) (total-width . 190) (total-height . 48) (normal-height . 1.0) (normal-width . 1.0) (combination-limit)
 (hc (pixel-width . 1896) (pixel-height . 252) (total-width . 190) (total-height . 12) (normal-height . 0.25225225225225223) (normal-width . 1.0) (combination-limit)
     (leaf (pixel-width . 950) (pixel-height . 252) (total-width . 95) (total-height . 12) (normal-height . 1.0) (normal-width . 0.501054852320675)
           (parameters (gdb-buffer-type . gdb-breakpoints-buffer))
           (buffer " *gdb-placeholder*" (selected)
                   (hscroll . 0) (fringes 8 8 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil)
                   (vscroll . 0) (dedicated . t) (point . 1) (start . 1)))
     (leaf (pixel-width . 480) (pixel-height . 252) (total-width . 48) (total-height . 12) (normal-height . 1.0) (normal-width . 0.25316455696202533)
           (parameters (gdb-buffer-type . gdb-stack-buffer))
           (buffer " *gdb-placeholder*" (selected)
                   (hscroll . 0) (fringes 8 8 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil)
                   (vscroll . 0) (dedicated . t) (point . 1) (start . 1)))
     (leaf (last . t) (pixel-width . 466) (pixel-height . 252) (total-width . 47) (total-height . 12) (normal-height . 1.0) (normal-width . 0.24578059071729957)
           (parameters (gdb-buffer-type . gdb-locals-buffer))
           (buffer " *gdb-placeholder*" (selected)
                   (hscroll . 0) (fringes 8 8 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil)
                   (vscroll . 0) (dedicated . t) (point . 1) (start . 1))))
 (hc (pixel-width . 1896) (pixel-height . 504) (total-width . 190) (total-height . 24) (normal-height . 0.5045045045045045) (normal-width . 1.0) (combination-limit)
     (leaf (pixel-width . 950) (pixel-height . 504) (total-width . 95) (total-height . 24) (normal-height . 1.0) (normal-width . 0.501054852320675)
           (parameters (gdb-buffer-type . source))
           (buffer " *gdb-placeholder*" (selected)
                   (hscroll . 0) (fringes 8 8 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil)
                   (vscroll . 0) (dedicated) (point . 1) (start . 1)))
     (vc (last . t) (pixel-width . 946) (pixel-height . 504) (total-width . 95) (total-height . 24) (normal-height . 1.0) (normal-width . 0.4989451476793249) (combination-limit)
         (leaf (pixel-width . 946) (pixel-height . 252) (total-width . 95) (total-height . 12) (normal-height . 0.5) (normal-width . 1.0)
               (parameters (gdb-buffer-type . gdb-disassembly-buffer))
               (buffer " *gdb-placeholder*" (selected)
                       (hscroll . 0) (fringes 8 8 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil)
                       (vscroll . 0) (dedicated . t) (point . 1) (start . 1)))
         (leaf (last . t) (pixel-width . 946) (pixel-height . 252) (total-width . 95) (total-height . 12) (normal-height . 0.5) (normal-width . 1.0)
               (parameters (gdb-buffer-type . gdb-memory-buffer))
               (buffer " *gdb-placeholder*" (selected . t)
                       (hscroll . 0) (fringes 8 8 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil)
                       (vscroll . 0) (dedicated . t) (point . 1) (start . 1)))))
 (hc (last . t) (pixel-width . 1896) (pixel-height . 243) (total-width . 190) (total-height . 12) (normal-height . 0.24324324324324326) (normal-width . 1.0) (combination-limit)
     (leaf (pixel-width . 950) (pixel-height . 243) (total-width . 95) (total-height . 12) (normal-height . 1.0) (normal-width . 0.501054852320675)
           (parameters (gdb-buffer-type . command))
           (buffer " *gdb-placeholder*" (selected)
                   (hscroll . 0) (fringes 8 8 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil)
                   (vscroll . 0) (dedicated) (point . 1) (start . 1)))
     (leaf (last . t) (pixel-width . 946) (pixel-height . 243) (total-width . 95) (total-height . 12) (normal-height . 1.0) (normal-width . 0.4989451476793249)
           (parameters (gdb-buffer-type . gdb-inferior-io))
           (buffer " *gdb-placeholder*" (selected)
                   (hscroll . 0) (fringes 8 8 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil)
                   (vscroll . 0) (dedicated . t) (point . 1) (start . 1)))))
