;; `cnfonts--custom-set-fontsnames' 结构与 `cnfonts--fontnames-fallback' 相同。
(setq cnfonts--custom-set-fontnames
      '(
        ("UbuntuMono Nerd Font Mono" "NotoSansM Nerd Font" "VictorMono Nerd Font Propo" "NotoSerif Nerd Font Propo" "UbuntuMono Nerd Font" "VictorMono Nerd Font Mono" "NotoSans Nerd Font" "JetBrainsMono Nerd Font Propo" "Standard Symbols PS" "Noto Sans CJK TC" "Noto Serif CJK KR" "NotoSansM Nerd Font Propo" "NotoSerif Nerd Font" "Noto Serif CJK TC" "VictorMono Nerd Font" "NotoSans Nerd Font Propo" "URW Gothic" "SauceCodePro Nerd Font Propo" "JetBrainsMonoNL Nerd Font" "UbuntuMono Nerd Font Propo" "SauceCodePro Nerd Font Mono" "NotoSansM Nerd Font Mono" "JetBrainsMono Nerd Font" "Noto Sans CJK KR" "Noto Serif CJK JP" "Nimbus Roman" "Noto Sans CJK SC" "Noto Serif CJK HK" "Source Code Pro" "Noto Serif CJK SC" "Noto Sans CJK HK" "xos4 Terminus" "Mononoki Nerd Font Mono" "SourceCodeVF" "Noto Sans CJK JP" "Sarasa Mono SC Nerd" "JetBrainsMonoNL Nerd Font Propo" "JetBrainsMonoNL Nerd Font Mono" "JetBrainsMono Nerd Font Mono" "Hack Nerd Font Propo" "SauceCodePro Nerd Font" "Comic Mono" "Cantarell" "Nimbus Sans" "Noto Sans Mono CJK SC" "Noto Sans Mono CJK TC" "Noto Sans Mono CJK JP" "Noto Sans Mono CJK HK" "Noto Sans Mono CJK KR" "FreeSerif" "Nimbus Mono PS" "Terminus" "WenQuanYi Micro Hei Mono" "Nimbus Sans Narrow" "URW Bookman" "Mononoki Nerd Font Propo" "NotoMono Nerd Font Mono" "C059" "Liberation Mono" "Sarasa Mono SC Wide Nerd" "github-octicons" "NotoMono Nerd Font Propo" "Material Icons" "all-the-icons" "WenQuanYi Micro Hei" "Mononoki Nerd Font" "Hack Nerd Font Mono" "Z003" "D050000L" "Hack Nerd Font" "Liberation Serif" "Liberation Sans" "Monaco" "file-icons" "FreeSans" "Noto Color Emoji" "NotoMono Nerd Font" "FontAwesome" "P052" "FreeMono" "HanaMinA" "HanaMinB" "Weather Icons" "Consolas" "DejaVu Sans Mono" "Droid Sans Mono" "PragmataPro Mono" "Courier" "Courier New" "Ubuntu Mono" "MonacoB" "MonacoB2" "MonacoBSemi" "Droid Sans Mono Pro" "Inconsolata" "Lucida Console" "Envy Code R" "Andale Mono" "Lucida Sans Typewriter" "monoOne" "Lucida Typewriter" "Panic Sans" "Hack" "Bitstream Vera Sans Mono" "HyperFont" "PT Mono" "Ti92Pluspc" "Excalibur Monospace" "Menlof" "Cousine" "Fira Mono" "Lekton" "M+ 1mn" "BPmono" "Free Mono" "Anonymous Pro" "ProFont" "ProFontWindows" "Latin Modern Mono" "Code 2002" "ProggyCleanTT" "ProggyTinyTT" "Iosevka Term" "Inconsolata-dz" "American Typewriter" "Menlo" "Anka/Coder Condensed" "Fantasque Sans Mono" "M+ 1m" "CamingoCode" "Office Code Pro" "Roboto Mono" "Input Mono" "Courier Prime Code" "NanumGothicCoding" "Monoid" "Edlo" "Iosevka" "Mononoki" "Robot Mono" "Fantasque" "Fira Code" "Go Mono" "Noto Sans Mono CJK" "InputMonoCompressed" "Hasklig" "FantasqueSansMono" "AnonymousPro" "Arimo" "D2Coding" "Inconsolata-g" "Noto Mono" "ProFont for Powerline" "Meslo" "Meslo Dotted" "Symbol Neu" "Tinos" "Space Mono" "SFMono Nerd Font")
        ("WenQuanYi Micro Hei Mono" "NotoSansM Nerd Font" "VictorMono Nerd Font Propo" "NotoSerif Nerd Font Propo" "UbuntuMono Nerd Font" "VictorMono Nerd Font Mono" "NotoSans Nerd Font" "JetBrainsMono Nerd Font Propo" "Standard Symbols PS" "Noto Sans CJK TC" "Noto Serif CJK KR" "NotoSansM Nerd Font Propo" "NotoSerif Nerd Font" "Noto Serif CJK TC" "VictorMono Nerd Font" "NotoSans Nerd Font Propo" "URW Gothic" "SauceCodePro Nerd Font Propo" "JetBrainsMonoNL Nerd Font" "UbuntuMono Nerd Font Propo" "SauceCodePro Nerd Font Mono" "NotoSansM Nerd Font Mono" "JetBrainsMono Nerd Font" "Noto Sans CJK KR" "Noto Serif CJK JP" "Nimbus Roman" "Noto Sans CJK SC" "Noto Serif CJK HK" "Source Code Pro" "Noto Serif CJK SC" "Noto Sans CJK HK" "xos4 Terminus" "Mononoki Nerd Font Mono" "SourceCodeVF" "Noto Sans CJK JP" "Sarasa Mono SC Nerd" "JetBrainsMonoNL Nerd Font Propo" "JetBrainsMonoNL Nerd Font Mono" "JetBrainsMono Nerd Font Mono" "Hack Nerd Font Propo" "SauceCodePro Nerd Font" "Comic Mono" "Cantarell" "Nimbus Sans" "Noto Sans Mono CJK SC" "Noto Sans Mono CJK TC" "Noto Sans Mono CJK JP" "Noto Sans Mono CJK HK" "Noto Sans Mono CJK KR" "FreeSerif" "Nimbus Mono PS" "Terminus" "Nimbus Sans Narrow" "URW Bookman" "Mononoki Nerd Font Propo" "NotoMono Nerd Font Mono" "C059" "Liberation Mono" "Sarasa Mono SC Wide Nerd" "github-octicons" "NotoMono Nerd Font Propo" "Material Icons" "all-the-icons" "WenQuanYi Micro Hei" "Mononoki Nerd Font" "Hack Nerd Font Mono" "Z003" "D050000L" "Hack Nerd Font" "Liberation Serif" "UbuntuMono Nerd Font Mono" "Liberation Sans" "Monaco" "file-icons" "FreeSans" "Noto Color Emoji" "NotoMono Nerd Font" "FontAwesome" "P052" "FreeMono" "HanaMinA" "HanaMinB" "Weather Icons" "微软雅黑" "Microsoft Yahei" "Microsoft YaHei Mono" "Microsoft_Yahei" "Ubuntu Mono" "文泉驿等宽微米黑" "文泉驿等宽正黑" "黑体" "Source Han Serif CN" "Source Han Sans CN" "思源黑体 CN" "思源宋体 CN" "Hiragino Sans GB" "文泉驿正黑" "文泉驿点阵正黑" "SimHei" "SimSun" "NSimSun" "FangSong" "KaiTi" "FangSong_GB2312" "KaiTi_GB2312" "LiSu" "YouYuan" "新宋体" "宋体" "楷体_GB2312" "仿宋_GB2312" "幼圆" "隶书" "STXihei" "STKaiti" "STSong" "STFangsong" "STXingkai" "华文仿宋" "华文行楷" "华文细黑" "华文楷体")
        ("HanaMinB" "NotoSansM Nerd Font" "VictorMono Nerd Font Propo" "NotoSerif Nerd Font Propo" "UbuntuMono Nerd Font" "VictorMono Nerd Font Mono" "NotoSans Nerd Font" "JetBrainsMono Nerd Font Propo" "Standard Symbols PS" "Noto Sans CJK TC" "Noto Serif CJK KR" "NotoSansM Nerd Font Propo" "NotoSerif Nerd Font" "Noto Serif CJK TC" "VictorMono Nerd Font" "NotoSans Nerd Font Propo" "URW Gothic" "SauceCodePro Nerd Font Propo" "JetBrainsMonoNL Nerd Font" "UbuntuMono Nerd Font Propo" "SauceCodePro Nerd Font Mono" "NotoSansM Nerd Font Mono" "JetBrainsMono Nerd Font" "Noto Sans CJK KR" "Noto Serif CJK JP" "Nimbus Roman" "Noto Sans CJK SC" "Noto Serif CJK HK" "Source Code Pro" "Noto Serif CJK SC" "Noto Sans CJK HK" "xos4 Terminus" "Mononoki Nerd Font Mono" "SourceCodeVF" "Noto Sans CJK JP" "Sarasa Mono SC Nerd" "JetBrainsMonoNL Nerd Font Propo" "JetBrainsMonoNL Nerd Font Mono" "JetBrainsMono Nerd Font Mono" "Hack Nerd Font Propo" "SauceCodePro Nerd Font" "Comic Mono" "Cantarell" "Nimbus Sans" "Noto Sans Mono CJK SC" "Noto Sans Mono CJK TC" "Noto Sans Mono CJK JP" "Noto Sans Mono CJK HK" "Noto Sans Mono CJK KR" "FreeSerif" "Nimbus Mono PS" "Terminus" "WenQuanYi Micro Hei Mono" "Nimbus Sans Narrow" "URW Bookman" "Mononoki Nerd Font Propo" "NotoMono Nerd Font Mono" "C059" "Liberation Mono" "Sarasa Mono SC Wide Nerd" "github-octicons" "NotoMono Nerd Font Propo" "Material Icons" "all-the-icons" "WenQuanYi Micro Hei" "Mononoki Nerd Font" "Hack Nerd Font Mono" "Z003" "D050000L" "Hack Nerd Font" "Liberation Serif" "UbuntuMono Nerd Font Mono" "Liberation Sans" "Monaco" "file-icons" "FreeSans" "Noto Color Emoji" "NotoMono Nerd Font" "FontAwesome" "P052" "FreeMono" "HanaMinA" "Weather Icons" "SimSun-ExtB" "MingLiU-ExtB" "PMingLiU-ExtB" "MingLiU_HKSCS-ExtB" "Hanazono Mincho" "Hanazono Mincho A" "Hanazono Mincho B" "Hanazono Mincho C" "Hanazono Mincho Ex" "Hanazono Mincho Ex A1" "Hanazono Mincho Ex A2" "Hanazono Mincho Ex B" "Hanazono Mincho Ex C" "Hanazono Mincho I")
        ("Sarasa Mono SC Nerd" "NotoSansM Nerd Font" "VictorMono Nerd Font Propo" "NotoSerif Nerd Font Propo" "UbuntuMono Nerd Font" "VictorMono Nerd Font Mono" "NotoSans Nerd Font" "JetBrainsMono Nerd Font Propo" "Standard Symbols PS" "Noto Sans CJK TC" "Noto Serif CJK KR" "NotoSansM Nerd Font Propo" "NotoSerif Nerd Font" "Noto Serif CJK TC" "VictorMono Nerd Font" "NotoSans Nerd Font Propo" "URW Gothic" "SauceCodePro Nerd Font Propo" "JetBrainsMonoNL Nerd Font" "UbuntuMono Nerd Font Propo" "SauceCodePro Nerd Font Mono" "NotoSansM Nerd Font Mono" "JetBrainsMono Nerd Font" "Noto Sans CJK KR" "Noto Serif CJK JP" "Nimbus Roman" "Noto Sans CJK SC" "Noto Serif CJK HK" "Source Code Pro" "Noto Serif CJK SC" "Noto Sans CJK HK" "xos4 Terminus" "Mononoki Nerd Font Mono" "SourceCodeVF" "Noto Sans CJK JP" "JetBrainsMonoNL Nerd Font Propo" "JetBrainsMonoNL Nerd Font Mono" "JetBrainsMono Nerd Font Mono" "Hack Nerd Font Propo" "SauceCodePro Nerd Font" "Comic Mono" "Cantarell" "Nimbus Sans" "Noto Sans Mono CJK SC" "Noto Sans Mono CJK TC" "Noto Sans Mono CJK JP" "Noto Sans Mono CJK HK" "Noto Sans Mono CJK KR" "FreeSerif" "Nimbus Mono PS" "Terminus" "WenQuanYi Micro Hei Mono" "Nimbus Sans Narrow" "URW Bookman" "Mononoki Nerd Font Propo" "NotoMono Nerd Font Mono" "C059" "Liberation Mono" "Sarasa Mono SC Wide Nerd" "github-octicons" "NotoMono Nerd Font Propo" "Material Icons" "all-the-icons" "WenQuanYi Micro Hei" "Mononoki Nerd Font" "Hack Nerd Font Mono" "Z003" "D050000L" "Hack Nerd Font" "Liberation Serif" "UbuntuMono Nerd Font Mono" "Liberation Sans" "Monaco" "file-icons" "FreeSans" "Noto Color Emoji" "NotoMono Nerd Font" "FontAwesome" "P052" "FreeMono" "HanaMinA" "HanaMinB" "Weather Icons" "Segoe UI Symbol" "Symbola" "Standard Symbols L")
        ("Sarasa Mono SC Nerd" "NotoSansM Nerd Font" "VictorMono Nerd Font Propo" "NotoSerif Nerd Font Propo" "UbuntuMono Nerd Font" "VictorMono Nerd Font Mono" "NotoSans Nerd Font" "JetBrainsMono Nerd Font Propo" "Standard Symbols PS" "Noto Sans CJK TC" "Noto Serif CJK KR" "NotoSansM Nerd Font Propo" "NotoSerif Nerd Font" "Noto Serif CJK TC" "VictorMono Nerd Font" "NotoSans Nerd Font Propo" "URW Gothic" "SauceCodePro Nerd Font Propo" "JetBrainsMonoNL Nerd Font" "UbuntuMono Nerd Font Propo" "SauceCodePro Nerd Font Mono" "NotoSansM Nerd Font Mono" "JetBrainsMono Nerd Font" "Noto Sans CJK KR" "Noto Serif CJK JP" "Nimbus Roman" "Noto Sans CJK SC" "Noto Serif CJK HK" "Source Code Pro" "Noto Serif CJK SC" "Noto Sans CJK HK" "xos4 Terminus" "Mononoki Nerd Font Mono" "SourceCodeVF" "Noto Sans CJK JP" "JetBrainsMonoNL Nerd Font Propo" "JetBrainsMonoNL Nerd Font Mono" "JetBrainsMono Nerd Font Mono" "Hack Nerd Font Propo" "SauceCodePro Nerd Font" "Comic Mono" "Cantarell" "Nimbus Sans" "Noto Sans Mono CJK SC" "Noto Sans Mono CJK TC" "Noto Sans Mono CJK JP" "Noto Sans Mono CJK HK" "Noto Sans Mono CJK KR" "FreeSerif" "Nimbus Mono PS" "Terminus" "WenQuanYi Micro Hei Mono" "Nimbus Sans Narrow" "URW Bookman" "Mononoki Nerd Font Propo" "NotoMono Nerd Font Mono" "C059" "Liberation Mono" "Sarasa Mono SC Wide Nerd" "github-octicons" "NotoMono Nerd Font Propo" "Material Icons" "all-the-icons" "WenQuanYi Micro Hei" "Mononoki Nerd Font" "Hack Nerd Font Mono" "Z003" "D050000L" "Hack Nerd Font" "Liberation Serif" "UbuntuMono Nerd Font Mono" "Liberation Sans" "Monaco" "file-icons" "FreeSans" "Noto Color Emoji" "NotoMono Nerd Font" "FontAwesome" "P052" "FreeMono" "HanaMinA" "HanaMinB" "Weather Icons" "NanumGothic" "Arial Unicode MS" "MS Gothic" "Lucida Sans Unicode")
        ))

;; `cnfonts--custom-set-fontsizes' 结构与 `cnfonts--fontsizes-fallback' 相同。
(setq cnfonts--custom-set-fontsizes
      '(
        (6    6.0  6.0  6.0  6   )
        (7    7.5  7.5  7.5  7.5 )
        (8    9.0  9    9.0  9.0 )
        (9    9.0  9.0  9.0  9   )
        (10   10.5 10.5 10.5 10.5)
        (11   12.0 12.0 12.0 12.0)
        (11.5 12.0 12.0 12.0 12.0)
        (12   12.0 12.0 12.0 12  )
        (12.5 13.5 13.5 13.5 13.5)
        (13   13.5 13.5 13.5 13.5)
        (13.5 13.5 13.5 13.5 13.5)
        (14   15.0 15.0 15.0 15.0)
        (14.5 15.0 15.0 15.0 15.0)
        (15   15.0 15.0 15.0 15  )
        (16   16.5 16.5 16.5 16.5)
        (18   18.0 18.0 18.0 18  )
        (20   21.0 21.0 21.0 21.0)
        (22   22.5 22.5 22.5 22.5)
        (24   24.0 24.0 24.0 24  )
        (26   27.0 27.0 27.0 27.0)
        (28   28.5 28.5 28.5 28.5)
        (30   30.0 30.0 30.0 30  )
        (32   33.0 33.0 33.0 33.0)
        ))
