;; `cnfonts--custom-set-fontsnames' 结构与 `cnfonts--fontnames-fallback' 相同。
(setq cnfonts--custom-set-fontnames
      '(
        ("UbuntuMono Nerd Font" "Mononoki Nerd Font" "Mononoki Nerd Font Mono" "UbuntuMono Nerd Font Mono" "JetBrainsMono Nerd Font Mono" "JetBrainsMono Nerd Font" "JetBrainsMonoNL Nerd Font" "Monaco" "FiraCode Nerd Font Mono" "Hack Nerd Font" "VictorMono Nerd Font Mono" "Source Code Variable" "NotoMono Nerd Font" "BlexMono Nerd Font" "InconsolataGo Nerd Font Mono" "Cantarell" "VictorMono Nerd Font" "Source Code Pro" "Liberation Serif" "Hack Nerd Font Mono" "Liberation Mono" "NotoSansMono Nerd Font" "PowerlineSymbols" "Terminus" "FiraCode Nerd Font" "Sarasa Mono SC Nerd" "SauceCodePro Nerd Font" "xos4 Terminus" "Noto Serif CJK SC" "BlexMono Nerd Font Mono" "Noto Serif CJK HK" "Noto Sans CJK SC" "Noto Serif CJK JP" "Noto Sans CJK KR" "NotoSerif Nerd Font" "InconsolataGo Nerd Font" "Noto Serif CJK TC" "Noto Serif CJK KR" "Noto Sans CJK TC" "Noto Sans CJK HK" "Noto Sans CJK JP" "Noto Sans Mono CJK SC" "Noto Sans Mono CJK TC" "Noto Sans Mono CJK JP" "Noto Sans Mono CJK HK" "Noto Sans Mono CJK KR" "NotoSans Nerd Font" "SauceCodePro Nerd Font Mono" "NotoSansMono Nerd Font Mono" "Sarasa Mono SC Wide Nerd" "NotoMono Nerd Font Mono" "Liberation Sans" "JetBrainsMonoNL Nerd Font Mono" "Noto Color Emoji" "Consolas" "DejaVu Sans Mono" "Droid Sans Mono" "PragmataPro Mono" "Courier" "Courier New" "Ubuntu Mono" "MonacoB" "MonacoB2" "MonacoBSemi" "Droid Sans Mono Pro" "Inconsolata" "Lucida Console" "Envy Code R" "Andale Mono" "Lucida Sans Typewriter" "monoOne" "Lucida Typewriter" "Panic Sans" "Hack" "Bitstream Vera Sans Mono" "HyperFont" "PT Mono" "Ti92Pluspc" "Excalibur Monospace" "Menlof" "Cousine" "Fira Mono" "Lekton" "M+ 1mn" "BPmono" "Free Mono" "Anonymous Pro" "ProFont" "ProFontWindows" "Latin Modern Mono" "Code 2002" "ProggyCleanTT" "ProggyTinyTT" "Iosevka Term" "Inconsolata-dz" "American Typewriter" "Menlo" "Anka/Coder Condensed" "Fantasque Sans Mono" "M+ 1m" "CamingoCode" "Office Code Pro" "Roboto Mono" "Input Mono" "Courier Prime Code" "NanumGothicCoding" "Monoid" "Edlo" "Iosevka" "Mononoki" "Robot Mono" "Fantasque" "Fira Code" "Go Mono" "Noto Sans Mono CJK" "InputMonoCompressed" "Hasklig" "FantasqueSansMono" "AnonymousPro" "Arimo" "D2Coding" "Inconsolata-g" "Noto Mono" "ProFont for Powerline" "Meslo" "Meslo Dotted" "Symbol Neu" "Tinos" "Space Mono" "SFMono Nerd Font" "WenQuanYi Micro Hei Mono" "WenQuanYi Micro Hei" "HanaMinA" "HanaMinB")
        ("文泉驿等宽微米黑" "WenQuanYi Micro Hei Mono" "Sarasa Mono SC Wide Nerd" "WenQuanYi Micro Hei" "VictorMono Nerd Font" "Cantarell" "FiraCode Nerd Font" "JetBrainsMonoNL Nerd Font" "Monaco" "BlexMono Nerd Font" "Noto Sans CJK SC" "Noto Sans CJK TC" "UbuntuMono Nerd Font" "JetBrainsMono Nerd Font Mono" "Noto Serif CJK KR" "Noto Serif CJK TC" "InconsolataGo Nerd Font" "NotoSerif Nerd Font" "Noto Sans CJK KR" "Noto Serif CJK JP" "Noto Serif CJK HK" "BlexMono Nerd Font Mono" "Source Code Pro" "Noto Serif CJK SC" "Noto Sans CJK HK" "xos4 Terminus" "Mononoki Nerd Font Mono" "SauceCodePro Nerd Font" "Noto Sans CJK JP" "Sarasa Mono SC Nerd" "Noto Sans Mono CJK SC" "Noto Sans Mono CJK TC" "Noto Sans Mono CJK JP" "Noto Sans Mono CJK HK" "Noto Sans Mono CJK KR" "NotoSans Nerd Font" "VictorMono Nerd Font Mono" "Terminus" "PowerlineSymbols" "NotoSansMono Nerd Font" "SauceCodePro Nerd Font Mono" "InconsolataGo Nerd Font Mono" "FiraCode Nerd Font Mono" "NotoSansMono Nerd Font Mono" "Liberation Mono" "Mononoki Nerd Font" "Hack Nerd Font Mono" "JetBrainsMono Nerd Font" "Hack Nerd Font" "Liberation Serif" "NotoMono Nerd Font Mono" "UbuntuMono Nerd Font Mono" "Liberation Sans" "JetBrainsMonoNL Nerd Font Mono" "NotoMono Nerd Font" "Source Code Variable" "Noto Color Emoji" "微软雅黑" "Microsoft Yahei" "Microsoft YaHei Mono" "Microsoft_Yahei" "Ubuntu Mono" "文泉驿等宽正黑" "黑体" "Source Han Serif CN" "Source Han Sans CN" "思源黑体 CN" "思源宋体 CN" "Hiragino Sans GB" "文泉驿正黑" "文泉驿点阵正黑" "SimHei" "SimSun" "NSimSun" "FangSong" "KaiTi" "FangSong_GB2312" "KaiTi_GB2312" "LiSu" "YouYuan" "新宋体" "宋体" "楷体_GB2312" "仿宋_GB2312" "幼圆" "隶书" "STXihei" "STKaiti" "STSong" "STFangsong" "STXingkai" "华文仿宋" "华文行楷" "华文细黑" "华文楷体" "HanaMinA" "HanaMinB")
        ("HanaMinB" "HanaMinA" "JetBrainsMono Nerd Font Mono" "UbuntuMono Nerd Font" "UbuntuMono Nerd Font Mono" "Noto Sans CJK TC" "Noto Serif CJK KR" "Noto Serif CJK TC" "InconsolataGo Nerd Font" "NotoSerif Nerd Font" "Noto Sans CJK KR" "Noto Serif CJK JP" "Noto Sans CJK SC" "Noto Serif CJK HK" "BlexMono Nerd Font Mono" "Source Code Pro" "Noto Serif CJK SC" "Noto Sans CJK HK" "xos4 Terminus" "Mononoki Nerd Font Mono" "SauceCodePro Nerd Font" "Noto Sans CJK JP" "Sarasa Mono SC Nerd" "FiraCode Nerd Font" "Cantarell" "Noto Sans Mono CJK SC" "Noto Sans Mono CJK TC" "Noto Sans Mono CJK JP" "Noto Sans Mono CJK HK" "Noto Sans Mono CJK KR" "NotoSans Nerd Font" "VictorMono Nerd Font Mono" "Terminus" "PowerlineSymbols" "NotoSansMono Nerd Font" "SauceCodePro Nerd Font Mono" "InconsolataGo Nerd Font Mono" "FiraCode Nerd Font Mono" "NotoSansMono Nerd Font Mono" "Liberation Mono" "Sarasa Mono SC Wide Nerd" "Mononoki Nerd Font" "Hack Nerd Font Mono" "JetBrainsMono Nerd Font" "Hack Nerd Font" "Liberation Serif" "NotoMono Nerd Font Mono" "Liberation Sans" "Monaco" "JetBrainsMonoNL Nerd Font Mono" "JetBrainsMonoNL Nerd Font" "NotoMono Nerd Font" "Source Code Variable" "Noto Color Emoji" "VictorMono Nerd Font" "BlexMono Nerd Font" "SimSun-ExtB" "MingLiU-ExtB" "PMingLiU-ExtB" "MingLiU_HKSCS-ExtB" "Hanazono Mincho" "Hanazono Mincho A" "Hanazono Mincho B" "Hanazono Mincho C" "Hanazono Mincho Ex" "Hanazono Mincho Ex A1" "Hanazono Mincho Ex A2" "Hanazono Mincho Ex B" "Hanazono Mincho Ex C" "Hanazono Mincho I" "WenQuanYi Micro Hei Mono" "WenQuanYi Micro Hei")
        ("Sarasa Mono SC Nerd" "JetBrainsMono Nerd Font Mono" "UbuntuMono Nerd Font" "Noto Sans CJK TC" "Noto Serif CJK KR" "Noto Serif CJK TC" "InconsolataGo Nerd Font" "NotoSerif Nerd Font" "Noto Sans CJK KR" "Noto Serif CJK JP" "Noto Sans CJK SC" "Noto Serif CJK HK" "BlexMono Nerd Font Mono" "Source Code Pro" "Noto Serif CJK SC" "Noto Sans CJK HK" "xos4 Terminus" "Mononoki Nerd Font Mono" "SauceCodePro Nerd Font" "Noto Sans CJK JP" "FiraCode Nerd Font" "Cantarell" "Noto Sans Mono CJK SC" "Noto Sans Mono CJK TC" "Noto Sans Mono CJK JP" "Noto Sans Mono CJK HK" "Noto Sans Mono CJK KR" "NotoSans Nerd Font" "VictorMono Nerd Font Mono" "Terminus" "PowerlineSymbols" "NotoSansMono Nerd Font" "SauceCodePro Nerd Font Mono" "InconsolataGo Nerd Font Mono" "FiraCode Nerd Font Mono" "NotoSansMono Nerd Font Mono" "Liberation Mono" "Sarasa Mono SC Wide Nerd" "Mononoki Nerd Font" "Hack Nerd Font Mono" "JetBrainsMono Nerd Font" "Hack Nerd Font" "Liberation Serif" "NotoMono Nerd Font Mono" "UbuntuMono Nerd Font Mono" "Liberation Sans" "Monaco" "JetBrainsMonoNL Nerd Font Mono" "JetBrainsMonoNL Nerd Font" "NotoMono Nerd Font" "Source Code Variable" "Noto Color Emoji" "VictorMono Nerd Font" "BlexMono Nerd Font" "Segoe UI Symbol" "Symbola" "Standard Symbols L" "WenQuanYi Micro Hei Mono" "WenQuanYi Micro Hei" "HanaMinA" "HanaMinB")
        ("Sarasa Mono SC Nerd" "JetBrainsMono Nerd Font Mono" "UbuntuMono Nerd Font" "Monaco" "Noto Sans CJK TC" "Noto Serif CJK KR" "Noto Serif CJK TC" "InconsolataGo Nerd Font" "NotoSerif Nerd Font" "Noto Sans CJK KR" "Noto Serif CJK JP" "Noto Sans CJK SC" "Noto Serif CJK HK" "BlexMono Nerd Font Mono" "Source Code Pro" "Noto Serif CJK SC" "Noto Sans CJK HK" "xos4 Terminus" "Mononoki Nerd Font Mono" "SauceCodePro Nerd Font" "Noto Sans CJK JP" "FiraCode Nerd Font" "Cantarell" "Noto Sans Mono CJK SC" "Noto Sans Mono CJK TC" "Noto Sans Mono CJK JP" "Noto Sans Mono CJK HK" "Noto Sans Mono CJK KR" "NotoSans Nerd Font" "VictorMono Nerd Font Mono" "Terminus" "PowerlineSymbols" "NotoSansMono Nerd Font" "SauceCodePro Nerd Font Mono" "InconsolataGo Nerd Font Mono" "FiraCode Nerd Font Mono" "NotoSansMono Nerd Font Mono" "Liberation Mono" "Sarasa Mono SC Wide Nerd" "Mononoki Nerd Font" "Hack Nerd Font Mono" "JetBrainsMono Nerd Font" "Hack Nerd Font" "Liberation Serif" "NotoMono Nerd Font Mono" "UbuntuMono Nerd Font Mono" "Liberation Sans" "JetBrainsMonoNL Nerd Font Mono" "JetBrainsMonoNL Nerd Font" "NotoMono Nerd Font" "Source Code Variable" "Noto Color Emoji" "VictorMono Nerd Font" "BlexMono Nerd Font" "NanumGothic" "Arial Unicode MS" "MS Gothic" "Lucida Sans Unicode" "WenQuanYi Micro Hei Mono" "WenQuanYi Micro Hei" "HanaMinA" "HanaMinB")
        ))

;; `cnfonts--custom-set-fontsizes' 结构与 `cnfonts--fontsizes-fallback' 相同。
(setq cnfonts--custom-set-fontsizes
      '(
        (6    6.0  6.0  6.0  6   )
        (7    7.5  7.5  7.5  7.5 )
        (8    9.0  9    9.0  9.0 )
        (9    9.0  9.0  9.0  9   )
        (10   10.5 10.5 10.5 10.5)
        (11   12.0 12.0 12.0 12.0)
        (11.5 12.0 12.0 12.0 12.0)
        (12   12.0 12.0 12.0 12  )
        (12.5 13.5 13.5 13.5 13.5)
        (13   13.5 13.5 13.5 13.5)
        (13.5 13.5 13.5 13.5 13.5)
        (14   15.0 15.0 15.0 15.0)
        (14.5 15.0 15.0 15.0 15.0)
        (15   15.0 15.0 15.0 15  )
        (16   16.5 16.5 16.5 16.5)
        (18   18.0 18.0 18.0 18  )
        (20   21.0 21.0 21.0 21.0)
        (22   22.5 22.5 22.5 22.5)
        (24   24.0 24.0 24.0 24  )
        (26   27.0 27.0 27.0 27.0)
        (28   28.5 28.5 28.5 28.5)
        (30   30.0 30.0 30.0 30  )
        (32   33.0 33.0 33.0 33.0)
        ))
